name: Update

on:
    workflow_call:
        inputs:
            bun-version:
              description: Bun Version
              required: false
              default: '1.1.4'
              type: string
        secrets:
            ORG_GH_RONIN_APP_ID:
              description: GitHub App ID
              required: true
            ORG_GH_RONIN_APP_PRIVATE_KEY:
              description: GitHub App Private Key
              required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    name: Auto-Merge
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ github.token }}

  lockfile:
    name: Lockfile Bump
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ORG_GH_RONIN_APP_ID }}
          private_key: ${{ secrets.ORG_GH_RONIN_APP_PRIVATE_KEY }}

      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ inputs.bun-version }}

      # Cache the local `node_modules` directory.
      - name: Restore npm Cache
        id: cache-node-modules
        uses: actions/cache@v3.0.11
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('patches/**') }}-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('patches/**') }}-
            ${{ runner.os }}-build-${{ hashFiles('patches/**') }}-
            ${{ runner.os }}-${{ hashFiles('patches/**') }}-

      - name: Install Dependencies
        run: |
            if [ -f "bunfig.ci.toml" ]; then
                bun install --config="bunfig.ci.toml"
            else
                bun install
            fi

      - name: Commit Changes and Push
        run: |
          # More details at https://stackoverflow.com/a/74071223
          git config --global user.name "ronin-app[bot]"
          git config --global user.email 135042755+ronin-app[bot]@users.noreply.github.com
          # Commit changes
          git fetch
          git checkout ${GITHUB_HEAD_REF}
          git pull origin ${GITHUB_HEAD_REF}
          git commit -a -m 'Bump `bun.lockb`' --no-verify --allow-empty
          git push origin ${GITHUB_HEAD_REF}
